const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

const { assetExts, sourceExts } = defaultConfig.resolver;

// Files generated by `npm run gen:types` use ESM/NodeNext-style imports
// (`./client.js` for `client.ts`), which Metro can't resolve. When a relative
// `.js` import can't be found, retry without the extension. This is a fallback,
// not an exact equivalent of webpack's `resolve.extensionAlias`: an actual `.js`
// file still wins over a `.ts` file with the same name.
const resolveRequest = (context, moduleName, platform) => {
  try {
    return context.resolveRequest(context, moduleName, platform);
  } catch (error) {
    if (!moduleName.startsWith(".") || !moduleName.endsWith(".js")) {
      throw error;
    }
    try {
      return context.resolveRequest(context, moduleName.slice(0, -3), platform);
    } catch {
      // The original error lists the paths tried for the import as written.
      throw error;
    }
  }
};

const config = {
  resolver: {
    assetExts: [...assetExts.filter((ext) => ext !== "svg"), "lottie"],
    sourceExts: [...sourceExts, "svg"],
    extraNodeModules: require("node-libs-react-native"),
    resolveRequest
  },
  transformer: {
    babelTransformerPath: require.resolve(
      "react-native-svg-transformer/react-native"
    ),
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true
      }
    })
  }
};

module.exports = mergeConfig(defaultConfig, config);
